### ISSUE TITLE
could you please share maskrcnn detection image?

### ISSUE THREAD

**Issue by maxwellfrom** [jediofgever/ROS_Raw_Kitti_Player#1]
Hi 
  You have done a great work, I am trying to use your code, however, I found the data from Kitti is not enough, Could you please share the maskrcnn detection images and maskrcnn detection labels? Than you very much!

**Comment by jediofgever** [comment]
Hi @maxwellfrom ,
I will share once I get my computer by today. However due to limited cloud usage I can share maybe just one scenario from KITTI , if you need more I suggest you to use maskrcnn under your setup. So which kitti scenerio are you interested in ?

**Comment by maxwellfrom** [comment]
This one: 2011_09_26_drive_0001. My email is 904995772@qq.com. Thanks a lot!

**Comment by maxwellfrom** [comment]
@jediofgever  Hello,  I'm sorry to bother you again， I assume you forgot to send me the data I asked before, cloud you please send that to me? I can make my own data according to yours, It will be really helpful. Thanks for your kind help!

**Comment by maxwellfrom** [comment]
Maybe you can send me any scenario data you have made, I can download corresponding data from Kitti.

**Comment by jediofgever** [comment]
Hi , sorry I didn’t receive my laptop , I had an issue with my laptop so I sent to service , it was supposed to be here yesterday but it didn’t. I didn’t forget it , once I laptop is here I will do ASAP , sorry again for inconvenience

**Comment by jediofgever** [comment]
https://drive.google.com/open?id=1f6hxpFloVp8Gwn6qe6GjmKyY15Le5E0j 
Here you go , for 3D box projected image , just create a empty folder under the scenerio directory , when you execute the program should create 3D box projected images. Let me know if you have further questions.

**Comment by maxwellfrom** [comment]
@jediofgever You have done me a great favor, thank you so much!

**Comment by jediofgever** [comment]
Were you able to reproduce similar results as in given screenshot ?

**Comment by maxwellfrom** [comment]
> Were you able to reproduce similar results as in given screenshot ?

Yes, I have got the same result as the screenshot shows.
