### ISSUE TITLE
fatal error: jsk_recognition_msgs/BoundingBox.h: No such file or directory

### ISSUE THREAD

**Issue by NoRomantic** [jediofgever/ROS_Raw_Kitti_Player#5]
I think it's a build order problem though, I can't figure out the dependencies between these packagaes. Could you please tell me how to build this package correctly?

**Comment by jediofgever** [comment]
Hi, 
Can you try this command
 rosdep install --from-paths src --ignore-src --rosdistro kinetic

**Comment by jediofgever** [comment]
Jsk_recognition is an external package that need to be installed for kinetic version, the above command will hopefully install the packages required

**Comment by NoRomantic** [comment]
@jediofgever  Hello, I've tried this command, but still comes out the same error.

**Comment by NoRomantic** [comment]
@jediofgever After executing this command:
`sudo apt-get install ros-kinetic-jsk-recognition-msgs`
I finally build this package successfullly.  So the reason caused this problem is that `jsk_recognition_msgs` package is missed.
Thanks for your excellent work and for your kindness.
