### ISSUE TITLE
can't get detected result in Rviz

### ISSUE THREAD

**Issue by hefc2016** [jediofgever/ROS_Raw_Kitti_Player#7]
Hello

I'm using ubuntu 16.04 LTS subsystem on WIN10, and I follow the guide to visualize the Kitti data without maskrcnn. The `catkin_make` is completed and when I run the `roslaunch kitti_ros kitti_ros_node.launch` but I can't get the picture which shared in Github.

rviz is started but no lidar/picture played in rviz window. I recevied below error in terminal window.

```
QXcbConnection: XCB error: 170 (Unknown), sequence: 163, resource id: 90, major code: 146 (Unknown), minor code: 20
[initCompute] Failed to allocate 256231980166827334 indices.
terminate called after throwing an instance of 'std::bad_array_new_length'
  what():  std::bad_array_new_length
[kitti_ros_node-2] process has died [pid 19345, exit code -6, cmd /home/hefc/catkin_ws/devel/lib/kitti_ros/kitti_ros_node __name:=kitti_ros_node __log:=/home/hefc/.ros/log/35ead340-70d3-11ea-955a-28f10e475296/kitti_ros_node-2.log].
log file: /home/hefc/.ros/log/35ead340-70d3-11ea-955a-28f10e475296/kitti_ros_node-2*.log
```
I'm not sure what the root casue is, it is regarding to the WIN 10 linux subsystem issue, or anything wrong with my ROS environemnt?

**Comment by jediofgever** [comment]
Hi,
I have not met this problem, I think this is caused by the limitations of virtual machine itself.
do you have access to an Ubuntu machine ? Sorry but cannot help much on this since I haven't worked on virtual machine in windows

**Comment by hefc2016** [comment]
Hello,
I tried in Windows Subsystem for Linux(WSL) and Ubuntu 16.04 both, they all have this problem. Finally I reinstall the pcl 1.8 which is required in source code, this issue fixed. Before that original pcl 1.7 and pcl 1.10 are installed in my environment. I think the problem is the PCL library not compatible.

thanks.
